buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
        maven { url = 'https://maven.parchmentmc.org' }
        maven { url = 'https://plugins.gradle.org/m2/' }
        mavenCentral()
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '5.1.+', changing: true
        classpath 'org.parchmentmc:librarian:1.+'
    }
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'org.parchmentmc.librarian.forgegradle'
apply plugin: 'eclipse'
apply plugin: 'maven-publish'
if (project.file('../gradletools.gradle').exists()) {
    apply from: '../gradletools.gradle'
} else {
    apply from: 'https://raw.githubusercontent.com/McJtyMods/MultiWorkspace/1.20_tech/gradletools.gradle'
}

repositories {
    maven { url "https://dvs1.progwml6.com/files/maven" } // JEI
    maven { url "https://maven.blamejared.com" } // Patchouli
    maven { url "https://maven.k-4u.nl" } // McJtyLib, TOP
    maven { url "https://maven.theillusivec4.top/" } // Curios
}

version = '1.0'
group = 'com.yourname.modid'
archivesBaseName = 'modid'
java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    //mappings channel: 'parchment', version: "2022.11.27-1.19.2"
        mappings channel: 'official', version: "${minecraft_version}"
//    accessTransformer = file('workspace/accesstransformer.cfg')

    runs {
        client {
            workingDirectory project.file('run')
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"

            mods {
                McJtyLib {
                    source project(':McJtyLib').sourceSets.main
                }
                DeepResonance {
                    source project(':DeepResonance').sourceSets.main
                }
                NEW {
                    source project(':NEW').sourceSets.main
                }
                Nice {
                    source project(':Nice').sourceSets.main
                }
                InteractionWheel {
                    source project(':InteractionWheel').sourceSets.main
                }
                Restrictions {
                    source project(':Restrictions').sourceSets.main
                }
                SignTastic {
                    source project(':SignTastic').sourceSets.main
                }
                InControl {
                    source project(':InControl').sourceSets.main
                }
                RFToolsStorage {
                    source project(':RFToolsStorage').sourceSets.main
                }
                RFToolsBase {
                    source project(':RFToolsBase').sourceSets.main
                }
                RFToolsControl {
                    source project(':RFToolsControl').sourceSets.main
                }
                RFToolsDimensions {
                    source project(':RFToolsDimensions').sourceSets.main
                }
                RFToolsPower {
                    source project(':RFToolsPower').sourceSets.main
                }
                RFToolsBuilder {
                    source project(':RFToolsBuilder').sourceSets.main
                }
                RFToolsUtility {
                    source project(':RFToolsUtility').sourceSets.main
                }
                LostCities {
                    source project(':LostCities').sourceSets.main
                }
                LostSouls {
                    source project(':LostSouls').sourceSets.main
                }
                Radar {
                    source project(':Radar').sourceSets.main
                }
                LostRuins {
                    source project(':LostRuins').sourceSets.main
                }
                LostEdit {
                    source project(':LostEdit').sourceSets.main
                }
                LostWorlds {
                    source project(':LostWorlds').sourceSets.main
                }
//                Wastify {
//                    source project(':Wastify').sourceSets.main
//                }
                Trinkets {
                    source project(':Trinkets').sourceSets.main
                }
                TheOneProbe {
                    source project(':TheOneProbe').sourceSets.main
                }
                ModXNet {
                    source project(':ModXNet').sourceSets.main
                }
                Hazardous {
                    source project(':Hazardous').sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"

            mods {
                McJtyLib {
                    source project(':McJtyLib').sourceSets.main
                }
                DeepResonance {
                    source project(':DeepResonance').sourceSets.main
                }
                NEW {
                    source project(':NEW').sourceSets.main
                }
                Nice {
                    source project(':Nice').sourceSets.main
                }
                InteractionWheel {
                    source project(':InteractionWheel').sourceSets.main
                }
                Restrictions {
                    source project(':Restrictions').sourceSets.main
                }
                SignTastic {
                    source project(':SignTastic').sourceSets.main
                }
                InControl {
                    source project(':InControl').sourceSets.main
                }
                RFToolsStorage {
                    source project(':RFToolsStorage').sourceSets.main
                }
                RFToolsBase {
                    source project(':RFToolsBase').sourceSets.main
                }
                RFToolsControl {
                    source project(':RFToolsControl').sourceSets.main
                }
                RFToolsDimensions {
                    source project(':RFToolsDimensions').sourceSets.main
                }
                RFToolsPower {
                    source project(':RFToolsPower').sourceSets.main
                }
                RFToolsBuilder {
                    source project(':RFToolsBuilder').sourceSets.main
                }
                RFToolsUtility {
                    source project(':RFToolsUtility').sourceSets.main
                }
                LostCities {
                    source project(':LostCities').sourceSets.main
                }
                LostSouls {
                    source project(':LostSouls').sourceSets.main
                }
                Radar {
                    source project(':Radar').sourceSets.main
                }
                LostRuins {
                    source project(':LostRuins').sourceSets.main
                }
                LostEdit {
                    source project(':LostEdit').sourceSets.main
                }
                LostWorlds {
                    source project(':LostWorlds').sourceSets.main
                }
//                Wastify {
//                    source project(':Wastify').sourceSets.main
//                }
                Trinkets {
                    source project(':Trinkets').sourceSets.main
                }
                TheOneProbe {
                    source project(':TheOneProbe').sourceSets.main
                }
//                ModBlocker {
//                    source project(':ModBlocker').sourceSets.main
//                }
                ModXNet {
                    source project(':ModXNet').sourceSets.main
                }
                Hazardous {
                    source project(':Hazardous').sourceSets.main
                }
            }
        }

        data {
            workingDirectory project.file('run')
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"

            args '--all', '--output', file('src/generated/resources/'), '--existing', sourceSets.main.resources.srcDirs[0]

            mods {
                McJtyLib {
                    source project(':McJtyLib').sourceSets.main
                }
                DeepResonance {
                    source project(':DeepResonance').sourceSets.main
                }
                NEW {
                    source project(':NEW').sourceSets.main
                }
                Nice {
                    source project(':Nice').sourceSets.main
                }
                InteractionWheel {
                    source project(':InteractionWheel').sourceSets.main
                }
                Restrictions {
                    source project(':Restrictions').sourceSets.main
                }
                SignTastic {
                    source project(':SignTastic').sourceSets.main
                }
                InControl {
                    source project(':InControl').sourceSets.main
                }
                RFToolsStorage {
                    source project(':RFToolsStorage').sourceSets.main
                }
                RFToolsBase {
                    source project(':RFToolsBase').sourceSets.main
                }
                RFToolsControl {
                    source project(':RFToolsControl').sourceSets.main
                }
                RFToolsDimensions {
                    source project(':RFToolsDimensions').sourceSets.main
                }
                RFToolsPower {
                    source project(':RFToolsPower').sourceSets.main
                }
                RFToolsBuilder {
                    source project(':RFToolsBuilder').sourceSets.main
                }
                RFToolsUtility {
                    source project(':RFToolsUtility').sourceSets.main
                }
                LostCities {
                    source project(':LostCities').sourceSets.main
                }
                LostSouls {
                    source project(':LostSouls').sourceSets.main
                }
                Radar {
                    source project(':Radar').sourceSets.main
                }
                LostRuins {
                    source project(':LostRuins').sourceSets.main
                }
                LostEdit {
                    source project(':LostEdit').sourceSets.main
                }
                LostWorlds {
                    source project(':LostWorlds').sourceSets.main
                }
//                Wastify {
//                    source project(':Wastify').sourceSets.main
//                }
                Trinkets {
                    source project(':Trinkets').sourceSets.main
                }
                TheOneProbe {
                    source project(':TheOneProbe').sourceSets.main
                }
//                ModBlocker {
//                    source project(':ModBlocker').sourceSets.main
//                }
                ModXNet {
                    source project(':ModXNet').sourceSets.main
                }
                Hazardous {
                    source project(':Hazardous').sourceSets.main
                }
            }
        }
    }
}

jars('mcmod')

def workspaceProject = { path ->
    dependencies.add('implementation', project(path)) {
        transitive = false
    }
}

dependencies {
    mc()
    jei()
    top()
    curios()
    patchouli()

    workspaceProject(':McJtyLib')
    workspaceProject(':DeepResonance')
    workspaceProject(':LostCities')
    workspaceProject(':LostSouls')
    workspaceProject(':LostRuins')
    workspaceProject(':LostEdit')
    workspaceProject(':LostWorlds')
//    workspaceProject(':Wastify')
    workspaceProject(':NEW')
    workspaceProject(':Nice')
    workspaceProject(':InteractionWheel')
    workspaceProject(':Restrictions')
    workspaceProject(':SignTastic')
    workspaceProject(':InControl')
    workspaceProject(':Radar')
    workspaceProject(':RFToolsStorage')
    workspaceProject(':RFToolsBase')
    workspaceProject(':RFToolsControl')
    workspaceProject(':RFToolsDimensions')
    workspaceProject(':RFToolsPower')
    workspaceProject(':RFToolsBuilder')
    workspaceProject(':RFToolsUtility')
    workspaceProject(':Trinkets')
    workspaceProject(':TheOneProbe')
//    workspaceProject(':ModBlocker')
    workspaceProject(':ModXNet')
    workspaceProject(':Hazardous')
}

// Example configuration to allow publishing using the maven-publish task
// we define a custom artifact that is sourced from the reobfJar output task
// and then declare that to be published
// Note you'll need to add a repository here
def reobfFile = file("$buildDir/reobfJar/output.jar")
def reobfArtifact = artifacts.add('default', reobfFile) {
    type 'jar'
    builtBy 'reobfJar'
}
publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact reobfArtifact
        }
    }
    repositories {
        maven {
            url "file:///${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.register('fixIntellijRunModules') {
    onlyIf { rootProject.file('.idea/runConfigurations').directory }

    doLast {
        def moduleName = (project.findProperty('intellij_run_module') ?: "${rootProject.name}.${project.name}.main").toString()
        rootProject.fileTree('.idea/runConfigurations') {
            include "${project.name}_run*.xml"
        }.each { runConfig ->
            def original = runConfig.getText('UTF-8')
            def updated = original.replaceAll(/<module name="[^"]*"\s*\/>/, "<module name=\"${moduleName}\"/>")
            if (updated != original) {
                runConfig.setText(updated, 'UTF-8')
            }
        }
    }
}

tasks.matching { it.name == 'genIntellijRuns' }.configureEach {
    finalizedBy 'fixIntellijRunModules'
}
